version: "3.7"

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.api.address=:8000"
      - "--entrypoints.portainer.address=:9000"
      - "--entrypoints.parking_permit.address=:8001"
      - "--entrypoints.student_card.address=:8002"
      - "--entrypoints.library_service.address=:8003"
      - "--entrypoints.library_client.address=:3001"
    ports:
      - 80:80
      - 3001:3001
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 8080:8080 # Traefik Dashboard
      - 9000:9000 # Portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`localhost`, `127.0.0.1`)"
      - "traefik.http.routers.portainer.entrypoints=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"


  postgres_backend:
    image: postgres:12
    container_name: db-backend
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5000:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:cached
    networks:
      - web

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: "postgresql://postgres:postgres@postgres_backend:5432/postgres"
    depends_on:
      - "postgres_backend"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`localhost`, `127.0.0.1`)"
      - "traefik.http.routers.backend.entrypoints=api"
      - "traefik.http.services.backend.loadbalancer.server.port=8888"
    networks:
      - web

  postgres_parking_permit:
    image: postgres:12
    container_name: db-parking_permit
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parking_permit
    ports:
      - "5001:5432"
    volumes:
      - parking-permit-db-data:/var/lib/postgresql/data:cached
    networks:
      - web

  parking_permit:
    build:
      context: ./services/parking_permit
      dockerfile: Dockerfile
    container_name: parking_permit
    volumes:
      - ./services/parking_permit:/app/:cached
    depends_on:
      - "postgres_parking_permit"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres_parking_permit:5432/parking_permit"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.parking_permit.rule=Host(`localhost`, `127.0.0.1`)"
      - "traefik.http.routers.parking_permit.entrypoints=parking_permit"
      - "traefik.http.services.parking_permit.loadbalancer.server.port=8001"
    networks:
      - web

  postgres_student_card:
    image: postgres:12
    container_name: db-student_card
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student_card
    ports:
      - "5002:5432"
    volumes:
      - student-card-db-data:/var/lib/postgresql/data:cached
    networks:
      - web

  student_card:
    build:
      context: ./services/student_card
      dockerfile: Dockerfile
    container_name: student_card
    volumes:
      - ./services/student_card:/app/:cached
    depends_on:
      - "postgres_student_card"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres_student_card:5432/student_card"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.student_card.rule=Host(`localhost`, `127.0.0.1`)"
      - "traefik.http.routers.student_card.entrypoints=student_card"
      - "traefik.http.services.student_card.loadbalancer.server.port=8002"
    networks:
      - web

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    stdin_open: true
    volumes:
      - "./frontend:/app:cached"
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`, `127.0.0.1`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - web
    
  library_client:
    container_name: library_client
    build:
      context: ./services/library_service/client
      dockerfile: Dockerfile
    networks:
      - web
    volumes:
      - ./services/library_service/client/src:/client/src
      - /services/library_service/client/node_modules
    depends_on:
      - library_api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.library_client.rule=Host(`localhost`, `127.0.0.1`)"
      - "traefik.http.routers.library_client.entrypoints=library_client"
      - "traefik.http.services.library_client.loadbalancer.server.port=3000"

  library_api:
    container_name: library_api
    build:
      context: ./services/library_service/api
      dockerfile: Dockerfile
    networks:
      - web
    volumes:
      - ./services/library_service/api/src:/server/src
      - /services/library_service/api/node_modules
    depends_on:
      - library_db
    environment:
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.library_api.rule=Host(`localhost`, `127.0.0.1`)"
      - "traefik.http.routers.library_api.entrypoints=library_service"
      - "traefik.http.services.library_api.loadbalancer.server.port=8003"

  library_db:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    networks:
      - web
    volumes:
      - library-db-data:/data/db
    env_file: ./services/library_service/api/.env


volumes:
  portainer-data:
  db-data:
  parking-permit-db-data:
  student-card-db-data:
  node_modules:
  library-db-data:

networks:
  web:
