version: '3.8'

services:
  db:
    image: postgres:13
    container_name: auth_psql
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  auth_service:
    build: .
    container_name: auth_service
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data:
